Assignment 3 Completed
deepgandhecha7/Assignment-3 pull request #1
Opened 2021-11-10 10:38 UTC by deepgandhecha7

![Screenshot (2)](https://user-images.githubusercontent.com/92928103/141098202-3c398479-577e-495e-a4db-c2de6cbcb23b.png)

2021-11-14 06:50 UTC, Abduliitr requested changes

2021-11-14 06:50 UTC, Abduliitr commented on index.html
> +            <img src="https://i.pinimg.com/736x/4f/88/32/4f8832629be791976d4407576798050f.jpg" width="100px">
add alt attribute in the img tag.

2021-11-14 06:50 UTC, Abduliitr commented
Correct (1 change requested)!

2021-11-14 06:54 UTC, deepgandhecha7 commented on index.html
> +            <img src="https://i.pinimg.com/736x/4f/88/32/4f8832629be791976d4407576798050f.jpg" width="100px">
Okay will do it

2021-11-14 08:19 UTC, Abduliitr approved these changes

2021-11-18 08:22 UTC, merged

2021-11-18 10:20 UTC, jdsamar commented
Code looks correct but the output seems not properly aligned